apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: up9k4udzv-nodejs 
  janus-idp.io/tekton: up9k4udzv-nodejs
  backstage.io/kubernetes-id: up9k4udzv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: up9k4udzv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml