apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: up9k4udzv-nodejs
  janus-idp.io/tekton: up9k4udzv-nodejs
  backstage.io/kubernetes-id: up9k4udzv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: up9k4udzv-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
