apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: up9k4udzv-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:91a79f393b410d8c06644b3fd42bef215824e8db@sha256:7a0e21644e19641fd9c1182a309baf421d81b91e6b6ae5ff47aaf6c4d9a53e37
          name: container-image
